USE [JasaServiceDB]
GO

/****** Object:  StoredProcedure [dbo].[ASSIGNMENT_TASK]    Script Date: 12/14/2016 01:40:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[ASSIGNMENT_TASK]
@ID_REQUEST VARCHAR(50)
AS
BEGIN
SELECT B.TOKEN, B.ID_USER, B.USER_NAME, B.NO_TELFON, C.ID_REQUEST, A.SERVICE_NAME
FROM TBL_SERVICE_PROVIDE A LEFT JOIN TBL_USER B ON A.FID_USER = B.ID_USER
OUTER APPLY (SELECT TOP 1 ID_REQUEST,FID_SERVICE, FID_USER_CREATE
				FROM TBL_REQUEST WHERE ID_REQUEST = @ID_REQUEST
				) C 
WHERE A.FID_SERVICE = C.FID_SERVICE
AND ID_USER NOT IN (SELECT CREATE_BY 
					FROM TBL_REQUEST_HISTORY 
					WHERE FID_REQUEST = C.ID_REQUEST)
END
GO


